apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-db-service
  name: inventory-db-service
spec:
  type: ClusterIP
  ports:
    - name: inventory-port
      port: 5434
      targetPort: inventory-port
  selector:
    app: inventory-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory-db
  name: inventory-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
        - image: postgres:14-alpine3.19
          imagePullPolicy: Always
          name: inventory-db
          ports:
            - name: inventory-port
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "inventory-db"
            - name: POSTGRES_USER
              value: "parth"
            - name: POSTGRES_PASSWORD
              value: "root"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: inventory-pvc
