apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment-db-service
  name: payment-db-service
spec:
  type: ClusterIP
  ports:
    - name: payment-db-port
      port: 5435
      targetPort: payment-db-port
  selector:
    app: payment-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-db
  name: payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - image: postgres:14-alpine3.19
          imagePullPolicy: Always
          name: payment-db
          ports:
            - name: payment-db-port
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "payment-db"
            - name: POSTGRES_USER
              value: "parth"
            - name: POSTGRES_PASSWORD
              value: "root"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: payment-pvc
