apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-service
  name: admin-service
spec:
  type: ClusterIP
  ports:
    - name: admin-port
      port: 8082
      targetPort: admin-port
  selector:
    app: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - image: omscs17/admin-service:latest
          imagePullPolicy: Always
          name: admin
          ports:
            - name: admin-port
              containerPort: 8082