apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-service
  name: inventory-service
spec:
  type: ClusterIP
  ports:
    - name: inventory-port
      port: 8083
      targetPort: inventory-port
  selector:
    app: inventory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - image: omscs17/inventory-service:latest
          imagePullPolicy: Always
          name: inventory
          ports:
            - name: inventory-port
              containerPort: 8083