apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment-service
  name: payment-service
spec:
  type: ClusterIP
  ports:
    - name: payment-port
      port: 8084
      targetPort: payment-port
  selector:
    app: payment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - image: omscs17/payment-service:latest
          imagePullPolicy: Always
          name: payment
          ports:
            - name: payment-port
              containerPort: 8084