global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'booking_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['booking-service:8080']
        labels:
          application: 'Booking Service Application'
  - job_name: 'admin_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['admin-service:8080']
        labels:
          application: 'Admin Service Application'
  - job_name: 'inventory_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory-service:8080']
        labels:
          application: 'Inventory Service Application'
  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8080']
        labels:
          application: 'Payment Service Application'