apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway-service
  name: api-gateway-service
spec:
  type: NodePort
  ports:
    - name: apigateway-port
      port: 8080
      targetPort: apigateway-port
      nodePort: 30004
  selector:
    app: api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - image: omscs17/api-gateway-service:latest
          imagePullPolicy: Always
          name: api-gateway
          ports:
            - name: apigateway-port
              containerPort: 8080
