apiVersion: v1
kind: PersistentVolume
metadata:
  name: admin-pv
  labels:
    type: local
    app: admin-db
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /edureka/admin/data/postgresql