apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-pvc
  labels:
    app: auth-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  volumeName: auth-pv