apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-pv
  labels:
    type: local
    app: auth-db
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /edureka/auth/data/postgresql