apiVersion: v1
kind: PersistentVolume
metadata:
  name: booking-pv
  labels:
    type: local
    app: booking-db
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /edureka/booking/data/postgresql