apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booking-pvc
  labels:
    app: booking-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  volumeName: booking-pv