apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-pvc
  labels:
    app: inventory-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  volumeName: inventory-pv