apiVersion: v1
kind: PersistentVolume
metadata:
  name: inventory-pv
  labels:
    type: local
    app: inventory-db
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /edureka/inventory/data/postgresql