apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-pvc
  labels:
    app: payment-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  volumeName: payment-pv