apiVersion: v1
kind: PersistentVolume
metadata:
  name: payment-pv
  labels:
    type: local
    app: payment-db
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /edureka/payment/data/postgresql