apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 3s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: 'admin_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['admin-service:8082']
            labels:
              application: 'Admin Service Application'
