apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-service
  name: grafana-service
spec:
  type: NodePort
  ports:
    - name: grafana-port
      port: 3000
      targetPort: grafana-port
      nodePort: 30008
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: grafana/grafana:latest
          imagePullPolicy: Always
          name: grafana
          ports:
            - name: grafana-port
              containerPort: 3000
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/datasources
      volumes: 
        - name: grafana-config
          configMap:
            name: grafana-config
