apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-service
  name: prometheus-service
spec:
  type: NodePort
  ports:
    - name: prometheus-port
      port: 9090
      targetPort: prometheus-port
      nodePort: 30007
  selector:
    app: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - image: prom/prometheus:latest
          imagePullPolicy: Always
          name: prometheus
          ports:
            - name: prometheus-port
              containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /etc/prometheus/data
      volumes: 
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-data
          hostPath:
            path: /edureka/prometheus/data
