apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
spec:
  type: ClusterIP
  ports:
    - name: zookeeper-port
      port: 2181
      targetPort: zookeeper-port
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - image: zookeeper:3.9.2-jre-17
          imagePullPolicy: Always
          name: zookeeper
          ports:
            - name: zookeeper-port
              containerPort: 2181